// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/**
 * Default [FirebaseOptions] for use with your Firebase apps.
 *
 * Example:
 * ```dart
 * import 'firebase_options.dart';
 * // ...
 * await Firebase.initializeApp(
 *   options: DefaultFirebaseOptions.currentPlatform,
 * );
 * ```
 */
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF26QczevLscGfZFw9jb7P_UsXubFivEQ',
    appId: '1:271515487957:web:6ab60299809b6aeba25c5c',
    messagingSenderId: '271515487957',
    projectId: 'hectoclash1',
    authDomain: 'hectoclash1.firebaseapp.com',
    storageBucket: 'hectoclash1.firebasestorage.app',
    measurementId: 'G-K6F4KTE625',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm7JUidIoVu8AjEID4i_3D6Henml3bPAQ',
    appId: '1:271515487957:android:5b0ec979f87a7fb1a25c5c',
    messagingSenderId: '271515487957',
    projectId: 'hectoclash1',
    storageBucket: 'hectoclash1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIwvMCjgq4XHad4Z8W8JmJL5xzxu1LG-0',
    appId: '1:271515487957:ios:93256bb88f677969a25c5c',
    messagingSenderId: '271515487957',
    projectId: 'hectoclash1',
    storageBucket: 'hectoclash1.firebasestorage.app',
    iosBundleId: 'com.example.hectoClash1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIwvMCjgq4XHad4Z8W8JmJL5xzxu1LG-0',
    appId: '1:271515487957:ios:93256bb88f677969a25c5c',
    messagingSenderId: '271515487957',
    projectId: 'hectoclash1',
    storageBucket: 'hectoclash1.firebasestorage.app',
    iosBundleId: 'com.example.hectoClash1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAF26QczevLscGfZFw9jb7P_UsXubFivEQ',
    appId: '1:271515487957:web:2e3134663e871a33a25c5c',
    messagingSenderId: '271515487957',
    projectId: 'hectoclash1',
    authDomain: 'hectoclash1.firebaseapp.com',
    storageBucket: 'hectoclash1.firebasestorage.app',
    measurementId: 'G-XW2WQW6C2L',
  );

}